name: My First Workflow
on:
  push:
    branches: 
    - main
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: List files in repo
        run: |
          echo "The rpo ${{github.repository}} contains the following files:"

  
  

          
